config/routes.rb
FinnesePractice::Application.routes.draw do

  devise_for :users
  resources :range_specifications

  resources :add_effects
  
  get "welcome/index"

  resources :macro_indicator_for_rounds

  resources :macro_indicator_options

  resources :macro_indicators

  resources :round_expenses

  resources :student_group_case_studies

  resources :players

  resources :selected_expense_for_rounds

  resources :expense_for_rounds

  resources :departments

  resources :expenses

  resources :rounds

  resources :roles

  resources :case_studies

  resources :student_group_users

  resources :student_groups

  resources :facilitator_groups

  resources :facilitators

  resources :clients

  get "select_brand/index"

  resources :survey_responses

    resources :student_group_surveys

    resources :survey_questions

    resources :question_options

    resources :questions

    resources :surveys

    resources :survey_positions

    resources :price_indices

    resources :brands

    resources :product_compositions

    resources :product_types

    resources :selected_channel_incentives

    resources :channel_incentive_for_rounds

    resources :sales

    resources :consumer_selections

    resources :channel_indices

    resources :uploads

    resources :channel_incentives

    resources :ad_indices

    resources :ad_effect_on_consumers

    resources :selected_media

    resources :media

    resources :consumers

    resources :consumer_types

    resources :incentive_effect_on_dealers

    resources :consumer_demographics

    resources :dealers

    resources :factories

    resources :welcome

    resources :assets

    resources :liabilities

    resources :loans

    resources :investment_types

    resources :investments

    resources :factory_input_prices

    resources :pnls

    resources :hr_incentive_for_rounds

    resources :selected_hr_incentives

    resources :hr_incentives

    resources :players

    resources :player_factories

    resources :productions

    resources :factory_inputs

   resources :employee_demographics

  resources :employees

  resources :employee_types

  resources :employee_expenses

  resources :expenses

  match 'get_production'=>"productions#get_production"

  match 'calculate_channel_index'=>'channel_indices#calculate_channel_index'

  match 'delete_all_channel_indices'=>"channel_indices#delete_all_channel_indices"

  match 'calculate_ad_index'=>'ad_indices#calculate_ad_index'

  match 'delete_all_ad_indices'=>"ad_indices#delete_all_ad_indices"

  match 'delete_all_consumer_selections' => 'consumer_selections#delete_all_consumer_selections'

  match 'calculate_consumer_selection' => 'consumer_selections#calculate_consumer_selection'

  match 'calculate_price_index'=>'price_indices#calculate_price_index'

  match 'delete_all_price_indices'=>"price_indices#delete_all_price_indices"

  match 'delete_all_sales'=>'sales#delete_all_sales'

  match 'get_sales'=>'sales#get_sales'

  match 'On_Select_Brand'=>'select_brand#On_Select_Brand'

  match 'mod_db'=>'player_factories#mod_db'

  match 'redirection'=>'welcome#redirection'

  match 'buy_factory'=>'player_factories#buy_factory'

   match 'manual_new'=>'pnls#manual_new'
  
  

   root :to => "welcome#index"

end

app/models/liability.rb
class Liability < ActiveRecord::Base

end

app/controllers/liabilities_controller.rb
class LiabilitiesController < ApplicationController
  # GET /liabilities
  # GET /liabilities.xml
  def index
    @liabilities = Liability.all
    @liability=Liability.new
       respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @liabilities }
    end
  end

  # GET /liabilities/1
  # GET /liabilities/1.xml
  def show
    @liability = Liability.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @liability }
    end
  end

  # GET /liabilities/new
  # GET /liabilities/new.xml
  def new
    @liability = Liability.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @liability }
    end
  end

  # GET /liabilities/1/edit
  def edit
    @liability = Liability.find(params[:id])
  end

  # POST /liabilities
  # POST /liabilities.xml
  def create
    @liability = Liability.new(params[:liability])



    respond_to do |format|
      if @liability.save
        @liability=Liability.last
        @asset=Asset.find(:last,:conditions => ['round_id=? AND player_id=?',@liability.round_id,@liability.player_id])



    @liability.net_worth= (@asset.fixed_assets + @asset.cash + @asset.investments + @asset.inventory)-(@liability.long_term_loans + @liability.short_term_loans);
    @liability.save
        format.html { redirect_to(:controller => :liabilities,:action => "index", :notice => 'Liability was successfully created.') }
        format.xml  { render :xml => @liability, :status => :created, :location => @liability }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @liability.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /liabilities/1
  # PUT /liabilities/1.xml
  def update
    @liability = Liability.find(params[:id])

    respond_to do |format|
      if @liability.update_attributes(params[:liability])
        format.html { redirect_to(@liability, :notice => 'Liability was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @liability.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /liabilities/1
  # DELETE /liabilities/1.xml
  def destroy
    @liability = Liability.find(params[:id])
    @liability.destroy

    respond_to do |format|
      format.html { redirect_to(liabilities_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/liabilities_helper.rb
module LiabilitiesHelper
end

app/views/liabilities/_form.html.erb
<%= form_for(@liability) do |f| %>
  <% if @liability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@liability.errors.count, "error") %> prohibited this liability from being saved:</h2>

      <ul>
      <% @liability.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :round_id %><br />
    <%= f.text_field :round_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br />
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :long_term_loans %><br />
    <%= f.text_field :long_term_loans %>
  </div>
  <div class="field">
    <%= f.label :short_term_loans %><br />
    <%= f.text_field :short_term_loans %>
  </div>


    <%= f.hidden_field :net_worth,:value=>params[:pid]%>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/liabilities/edit.html.erb
<h1>Editing liability</h1>

<%= render 'form' %>

<%= link_to 'Show', @liability %> |
<%= link_to 'Back', liabilities_path %>

app/views/liabilities/index.html.erb
<h1>Listing liabilities</h1>

<table>
  <tr>
    <th>Round</th>
    <th>Player</th>
    <th>Long term loans</th>
    <th>Short term loans</th>
    <th>Net worth</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @liabilities.each do |liability| %>
  <tr>
    <td><%= liability.round_id %></td>
    <td><%= liability.player_id %></td>
    <td><%= liability.long_term_loans %></td>
    <td><%= liability.short_term_loans %></td>
    <td><%= liability.net_worth %></td>
    <td><%= link_to 'Show', liability %></td>
    <td><%= link_to 'Edit', edit_liability_path(liability) %></td>
    <td><%= link_to 'Destroy', liability, :confirm => 'Are you sure?', :method => :delete %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Liability', new_liability_path %>

app/views/liabilities/new.html.erb
<h1>New liability</h1>

<%= render 'form' %>

<%= link_to 'Back', liabilities_path %>

app/views/liabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Round:</b>
  <%= @liability.round_id %>
</p>

<p>
  <b>Player:</b>
  <%= @liability.player_id %>
</p>

<p>
  <b>Long term loans:</b>
  <%= @liability.long_term_loans %>
</p>

<p>
  <b>Short term loans:</b>
  <%= @liability.short_term_loans %>
</p>

<p>
  <b>Net worth:</b>
  <%= @liability.net_worth %>
</p>


<%= link_to 'Edit', edit_liability_path(@liability) %> |
<%= link_to 'Back', liabilities_path %>