config/routes.rb
FinnesePractice::Application.routes.draw do

  devise_for :users
  resources :range_specifications

  resources :add_effects
  
  get "welcome/index"

  resources :macro_indicator_for_rounds

  resources :macro_indicator_options

  resources :macro_indicators

  resources :round_expenses

  resources :student_group_case_studies

  resources :players

  resources :selected_expense_for_rounds

  resources :expense_for_rounds

  resources :departments

  resources :expenses

  resources :rounds

  resources :roles

  resources :case_studies

  resources :student_group_users

  resources :student_groups

  resources :facilitator_groups

  resources :facilitators

  resources :clients

  get "select_brand/index"

  resources :survey_responses

    resources :student_group_surveys

    resources :survey_questions

    resources :question_options

    resources :questions

    resources :surveys

    resources :survey_positions

    resources :price_indices

    resources :brands

    resources :product_compositions

    resources :product_types

    resources :selected_channel_incentives

    resources :channel_incentive_for_rounds

    resources :sales

    resources :consumer_selections

    resources :channel_indices

    resources :uploads

    resources :channel_incentives

    resources :ad_indices

    resources :ad_effect_on_consumers

    resources :selected_media

    resources :media

    resources :consumers

    resources :consumer_types

    resources :incentive_effect_on_dealers

    resources :consumer_demographics

    resources :dealers

    resources :factories

    resources :welcome

    resources :assets

    resources :liabilities

    resources :loans

    resources :investment_types

    resources :investments

    resources :factory_input_prices

    resources :pnls

    resources :hr_incentive_for_rounds

    resources :selected_hr_incentives

    resources :hr_incentives

    resources :players

    resources :player_factories

    resources :productions

    resources :factory_inputs

   resources :employee_demographics

  resources :employees

  resources :employee_types

  resources :employee_expenses

  resources :expenses

  match 'get_production'=>"productions#get_production"

  match 'calculate_channel_index'=>'channel_indices#calculate_channel_index'

  match 'delete_all_channel_indices'=>"channel_indices#delete_all_channel_indices"

  match 'calculate_ad_index'=>'ad_indices#calculate_ad_index'

  match 'delete_all_ad_indices'=>"ad_indices#delete_all_ad_indices"

  match 'delete_all_consumer_selections' => 'consumer_selections#delete_all_consumer_selections'

  match 'calculate_consumer_selection' => 'consumer_selections#calculate_consumer_selection'

  match 'calculate_price_index'=>'price_indices#calculate_price_index'

  match 'delete_all_price_indices'=>"price_indices#delete_all_price_indices"

  match 'delete_all_sales'=>'sales#delete_all_sales'

  match 'get_sales'=>'sales#get_sales'

  match 'On_Select_Brand'=>'select_brand#On_Select_Brand'

  match 'mod_db'=>'player_factories#mod_db'

  match 'redirection'=>'welcome#redirection'

  match 'buy_factory'=>'player_factories#buy_factory'

   match 'manual_new'=>'pnls#manual_new'
  
  

   root :to => "welcome#index"

end

app/controllers/round_expenses_controller.rb
class RoundExpensesController < ApplicationController
  # GET /round_expenses
  # GET /round_expenses.xml
  def index
    @round_expenses = RoundExpense.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @round_expenses }
    end
  end

  # GET /round_expenses/1
  # GET /round_expenses/1.xml
  def show
    @round_expense = RoundExpense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @round_expense }
    end
  end

  # GET /round_expenses/new
  # GET /round_expenses/new.xml
  def new
    @round_expense = RoundExpense.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @round_expense }
    end
  end

  # GET /round_expenses/1/edit
  def edit
    @round_expense = RoundExpense.find(params[:id])
  end

  # POST /round_expenses
  # POST /round_expenses.xml
  def create
    @round_expense = RoundExpense.new(params[:round_expense])
    @round=Round.new(params[:round])
    respond_to do |format|
      if @round_expense.save
        format.html { redirect_to(@round_expense, :notice => 'Round expense was successfully created.') }
        format.xml  { render :xml => @round_expense, :status => :created, :location => @round_expense }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @round_expense.errors, :status => :unprocessable_entity }
      end
    end
    @round.save
  end

  # PUT /round_expenses/1
  # PUT /round_expenses/1.xml
  def update
    @round_expense = RoundExpense.find(params[:id])

    respond_to do |format|
      if @round_expense.update_attributes(params[:round_expense])
        format.html { redirect_to(@round_expense, :notice => 'Round expense was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @round_expense.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /round_expenses/1
  # DELETE /round_expenses/1.xml
  def destroy
    @round_expense = RoundExpense.find(params[:id])
    @round_expense.destroy

    respond_to do |format|
      format.html { redirect_to(round_expenses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/round_expenses_helper.rb
module RoundExpensesHelper
end

app/views/round_expenses/_form.html.erb
<%= form_for(@round_expense) do |f| %>
  <% if @round_expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round_expense.errors.count, "error") %> prohibited this round_expense from being saved:</h2>

      <ul>
      <% @round_expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :round_id %><br />
    <%= f.text_field :round_id %>
  </div>
  <div class="field">
    <%= f.label :expense_id %><br />
    <%= f.text_field :expense_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/round_expenses/edit.html.erb
<h1>Editing round_expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @round_expense %> |
<%= link_to 'Back', round_expenses_path %>

app/views/round_expenses/index.html.erb
<h1>Listing round_expenses</h1>

<table>
  <tr>
    <th>Round</th>
    <th>Expense</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @round_expenses.each do |round_expense| %>
  <tr>
    <td><%= round_expense.round_id %></td>
    <td><%= round_expense.expense_id %></td>
    <td><%= link_to 'Show', round_expense %></td>
    <td><%= link_to 'Edit', edit_round_expense_path(round_expense) %></td>
    <td><%= link_to 'Destroy', round_expense, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Round expense', new_round_expense_path %>

app/views/round_expenses/new.html.erb
<h1>New round_expense</h1>

<%= render 'form' %>

<%= link_to 'Back', round_expenses_path %>

app/views/round_expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Round:</b>
  <%= @round_expense.round_id %>
</p>

<p>
  <b>Expense:</b>
  <%= @round_expense.expense_id %>
</p>


<%= link_to 'Edit', edit_round_expense_path(@round_expense) %> |
<%= link_to 'Back', round_expenses_path %>