config/routes.rb
FinnesePractice::Application.routes.draw do

  devise_for :users
  resources :range_specifications

  resources :add_effects
  
  get "welcome/index"

  resources :macro_indicator_for_rounds

  resources :macro_indicator_options

  resources :macro_indicators

  resources :round_expenses

  resources :student_group_case_studies

  resources :players

  resources :selected_expense_for_rounds

  resources :expense_for_rounds

  resources :departments

  resources :expenses

  resources :rounds

  resources :roles

  resources :case_studies

  resources :student_group_users

  resources :student_groups

  resources :facilitator_groups

  resources :facilitators

  resources :clients

  get "select_brand/index"

  resources :survey_responses

    resources :student_group_surveys

    resources :survey_questions

    resources :question_options

    resources :questions

    resources :surveys

    resources :survey_positions

    resources :price_indices

    resources :brands

    resources :product_compositions

    resources :product_types

    resources :selected_channel_incentives

    resources :channel_incentive_for_rounds

    resources :sales

    resources :consumer_selections

    resources :channel_indices

    resources :uploads

    resources :channel_incentives

    resources :ad_indices

    resources :ad_effect_on_consumers

    resources :selected_media

    resources :media

    resources :consumers

    resources :consumer_types

    resources :incentive_effect_on_dealers

    resources :consumer_demographics

    resources :dealers

    resources :factories

    resources :welcome

    resources :assets

    resources :liabilities

    resources :loans

    resources :investment_types

    resources :investments

    resources :factory_input_prices

    resources :pnls

    resources :hr_incentive_for_rounds

    resources :selected_hr_incentives

    resources :hr_incentives

    resources :players

    resources :player_factories

    resources :productions

    resources :factory_inputs

   resources :employee_demographics

  resources :employees

  resources :employee_types

  resources :employee_expenses

  resources :expenses

  match 'get_production'=>"productions#get_production"

  match 'calculate_channel_index'=>'channel_indices#calculate_channel_index'

  match 'delete_all_channel_indices'=>"channel_indices#delete_all_channel_indices"

  match 'calculate_ad_index'=>'ad_indices#calculate_ad_index'

  match 'delete_all_ad_indices'=>"ad_indices#delete_all_ad_indices"

  match 'delete_all_consumer_selections' => 'consumer_selections#delete_all_consumer_selections'

  match 'calculate_consumer_selection' => 'consumer_selections#calculate_consumer_selection'

  match 'calculate_price_index'=>'price_indices#calculate_price_index'

  match 'delete_all_price_indices'=>"price_indices#delete_all_price_indices"

  match 'delete_all_sales'=>'sales#delete_all_sales'

  match 'get_sales'=>'sales#get_sales'

  match 'On_Select_Brand'=>'select_brand#On_Select_Brand'

  match 'mod_db'=>'player_factories#mod_db'

  match 'redirection'=>'welcome#redirection'

  match 'buy_factory'=>'player_factories#buy_factory'

   match 'manual_new'=>'pnls#manual_new'
  
  

   root :to => "welcome#index"

end

app/models/survey.rb
class Survey < ActiveRecord::Base
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # GET /surveys
  # GET /surveys.xml
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.xml
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.xml
  def new
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.xml
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to(@survey, :notice => 'Survey was successfully created.') }
        format.xml  { render :xml => @survey, :status => :created, :location => @survey }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @survey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.xml
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to(@survey, :notice => 'Survey was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @survey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.xml
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to(surveys_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :survey_position_id %><br />
    <%= f.text_field :survey_position_id %>
  </div>
  <div class="field">
    <%= f.label :facilitator_id %><br />
    <%= f.text_field :facilitator_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<h1>Listing surveys</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Survey position</th>
    <th>Facilitator</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @surveys.each do |survey| %>
  <tr>
    <td><%= survey.name %></td>
    <td><%= survey.survey_position_id %></td>
    <td><%= survey.facilitator_id %></td>
    <td><%= link_to 'Show', survey %></td>
    <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
    <td><%= link_to 'Destroy', survey, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @survey.name %>
</p>

<p>
  <b>Survey position:</b>
  <%= @survey.survey_position_id %>
</p>

<p>
  <b>Facilitator:</b>
  <%= @survey.facilitator_id %>
</p>


<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>