config/routes.rb
FinnesePractice::Application.routes.draw do

  devise_for :users
  resources :range_specifications

  resources :add_effects
  
  get "welcome/index"

  resources :macro_indicator_for_rounds

  resources :macro_indicator_options

  resources :macro_indicators

  resources :round_expenses

  resources :student_group_case_studies

  resources :players

  resources :selected_expense_for_rounds

  resources :expense_for_rounds

  resources :departments

  resources :expenses

  resources :rounds

  resources :roles

  resources :case_studies

  resources :student_group_users

  resources :student_groups

  resources :facilitator_groups

  resources :facilitators

  resources :clients

  get "select_brand/index"

  resources :survey_responses

    resources :student_group_surveys

    resources :survey_questions

    resources :question_options

    resources :questions

    resources :surveys

    resources :survey_positions

    resources :price_indices

    resources :brands

    resources :product_compositions

    resources :product_types

    resources :selected_channel_incentives

    resources :channel_incentive_for_rounds

    resources :sales

    resources :consumer_selections

    resources :channel_indices

    resources :uploads

    resources :channel_incentives

    resources :ad_indices

    resources :ad_effect_on_consumers

    resources :selected_media

    resources :media

    resources :consumers

    resources :consumer_types

    resources :incentive_effect_on_dealers

    resources :consumer_demographics

    resources :dealers

    resources :factories

    resources :welcome

    resources :assets

    resources :liabilities

    resources :loans

    resources :investment_types

    resources :investments

    resources :factory_input_prices

    resources :pnls

    resources :hr_incentive_for_rounds

    resources :selected_hr_incentives

    resources :hr_incentives

    resources :players

    resources :player_factories

    resources :productions

    resources :factory_inputs

   resources :employee_demographics

  resources :employees

  resources :employee_types

  resources :employee_expenses

  resources :expenses

  match 'get_production'=>"productions#get_production"

  match 'calculate_channel_index'=>'channel_indices#calculate_channel_index'

  match 'delete_all_channel_indices'=>"channel_indices#delete_all_channel_indices"

  match 'calculate_ad_index'=>'ad_indices#calculate_ad_index'

  match 'delete_all_ad_indices'=>"ad_indices#delete_all_ad_indices"

  match 'delete_all_consumer_selections' => 'consumer_selections#delete_all_consumer_selections'

  match 'calculate_consumer_selection' => 'consumer_selections#calculate_consumer_selection'

  match 'calculate_price_index'=>'price_indices#calculate_price_index'

  match 'delete_all_price_indices'=>"price_indices#delete_all_price_indices"

  match 'delete_all_sales'=>'sales#delete_all_sales'

  match 'get_sales'=>'sales#get_sales'

  match 'On_Select_Brand'=>'select_brand#On_Select_Brand'

  match 'mod_db'=>'player_factories#mod_db'

  match 'redirection'=>'welcome#redirection'

  match 'buy_factory'=>'player_factories#buy_factory'

   match 'manual_new'=>'pnls#manual_new'
  
  

   root :to => "welcome#index"

end

app/models/hr_incentive.rb
class HrIncentive < ActiveRecord::Base
end

app/controllers/hr_incentives_controller.rb
class HrIncentivesController < ApplicationController
  # GET /hr_incentives
  # GET /hr_incentives.xml
  def index
    @hr_incentives = HrIncentive.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @hr_incentives }
    end
  end

  # GET /hr_incentives/1
  # GET /hr_incentives/1.xml
  def show
    @hr_incentive = HrIncentive.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @hr_incentive }
    end
  end

  # GET /hr_incentives/new
  # GET /hr_incentives/new.xml
  def new
    @hr_incentive = HrIncentive.new
    @hr_incentives = HrIncentive.all

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @hr_incentive }
    end
  end

  # GET /hr_incentives/1/edit
  def edit
    @hr_incentive = HrIncentive.find(params[:id])
  end

  # POST /hr_incentives
  # POST /hr_incentives.xml
  def create
    @hr_incentive = HrIncentive.new(params[:hr_incentive])

    respond_to do |format|
      if @hr_incentive.save
        format.html { redirect_to(@hr_incentive, :notice => 'Hr incentive was successfully created.') }
        format.xml  { render :xml => @hr_incentive, :status => :created, :location => @hr_incentive }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @hr_incentive.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hr_incentives/1
  # PUT /hr_incentives/1.xml
  def update
    @hr_incentive = HrIncentive.find(params[:id])

    respond_to do |format|
      if @hr_incentive.update_attributes(params[:hr_incentive])
        format.html { redirect_to(@hr_incentive, :notice => 'Hr incentive was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @hr_incentive.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hr_incentives/1
  # DELETE /hr_incentives/1.xml
  def destroy
    @hr_incentive = HrIncentive.find(params[:id])
    @hr_incentive.destroy

    respond_to do |format|
      format.html { redirect_to(hr_incentives_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/hr_incentives_helper.rb
module HrIncentivesHelper
end

app/views/hr_incentives/_form.html.erb
<%= form_for(@hr_incentive) do |f| %>
  <% if @hr_incentive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hr_incentive.errors.count, "error") %> prohibited this hr_incentive from being saved:</h2>

      <ul>
      <% @hr_incentive.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hr_incentives/edit.html.erb
<h1>Editing hr_incentive</h1>

<%= render 'form' %>

<%= link_to 'Show', @hr_incentive %> |
<%= link_to 'Back', hr_incentives_path %>

app/views/hr_incentives/index.html.erb
<h1>Listing hr_incentives</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Active</th>
    <th>Cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hr_incentives.each do |hr_incentive| %>
  <tr>
    <td><%= hr_incentive.name %></td>
    <td><%= hr_incentive.active %></td>
    <td><%= hr_incentive.cost %></td>
    <td><%= link_to 'Show', hr_incentive %></td>
    <td><%= link_to 'Edit', edit_hr_incentive_path(hr_incentive) %></td>
    <td><%= link_to 'Destroy', hr_incentive, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hr incentive', new_hr_incentive_path %>

app/views/hr_incentives/new.html.erb
<h1>Listing hr_incentives</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Active</th>
    <th>Cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hr_incentives.each do |hr_incentive| %>
  <tr>
    <td><%= hr_incentive.name %></td>
    <td><%= hr_incentive.active %></td>
    <td><%= hr_incentive.cost %></td>
    <td><%= link_to 'Show', hr_incentive %></td>
    <td><%= link_to 'Edit', edit_hr_incentive_path(hr_incentive) %></td>
    <td><%= link_to 'Destroy', hr_incentive, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= render 'form' %>

<%= link_to 'Back',:controller => :welcome,:action => "index" %>

app/views/hr_incentives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hr_incentive.name %>
</p>

<p>
  <b>Active:</b>
  <%= @hr_incentive.active %>
</p>

<p>
  <b>Cost:</b>
  <%= @hr_incentive.cost %>
</p>


<%= link_to 'Edit', edit_hr_incentive_path(@hr_incentive) %> |
<%= link_to 'Back', hr_incentives_path %>